### ISSUE TITLE
pagodabox/na-lvs library not available anymore.

### ISSUE THREAD

**Issue by pananormalny** [nanopack/portal#10]
Hi guys!

The na-lvs library is not available anymore :(

The reference is here: https://github.com/nanopack/portal/blob/master/routes/server.go -line 15

If you have it locally please share with it somewhere, or try to put it in portal repo. 

Cheers!

**Comment by notxarb** [comment]
Thanks,

I've been working on a refactor for this project.
The na-lvs library is now found at https://github.com/nanobox-io/golang-lvs
I have a branch open on that repo to work with a branch on this repo. The branch on each repo is called feature/refactor.

I hope to have most of these things wrapped up in the next couple of days.
